spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/api_db
    username: postgres
    password: docker
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect